data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16

training:
  use_cuda: True
  epochs: 5
  random_seed: 42
  batch_size: 1
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "D:/Thesis/models"
  weights_dir: "D:/Thesis/models"