data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "random"
  input_size: 256
  clips_per_class: -1

training:
  specific_glosses: ['VERDWIJNEN-C', 'HOND-A']
  run_name: "test"
  use_cuda: True
  epochs: 50
  random_seed: 42
  batch_size: 16
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "D:/Thesis/models/i3d"
  weights_dir: "D:/Thesis/models"