data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "random"
  diagonal_videos_path: "/vol/tensusers5/jmartinez/datasets/diagonal_videos.gzip"
  use_diag_videos: False

training:
  specific_glosses: ["ZIEN-B", "EIGEN-A"] #["PT-1hand", "PO"]
  run_name: "exp1d"
  use_cuda: True
  epochs: 50
  random_seed: 42
  batch_size: 128
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "D:/Thesis/models"
  weights_dir: "D:/Thesis/models"