data:

  cngt_clips_path: "/vol/tensusers5/jmartinez/datasets/cngt_train_clips.zip"
  signbank_path: "/vol/tensusers5/jmartinez/datasets/NGT_Signbank_resized.zip"
  window_size: 16

training:
  run_name: "advanced_transformations"
  use_cuda: True
  epochs: 100
  random_seed: 42
  batch_size: 128
  init_lr: 0.01
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "/vol/tensusers5/jmartinez/models/i3d"
  weights_dir: "/vol/tensusers5/jmartinez/models"
