data:

  cngt_clips_path: "/vol/tensusers5/jmartinez/datasets/cngt_train_clips.zip"
  signbank_path: "/vol/tensusers5/jmartinez/datasets/NGT_Signbank_resized.zip"
  window_size: 64

training:

  epochs: 50
  random_seed: 42
  batch_size: 8
  init_lr: 0.1
  save_model: "/vol/tensusers5/jmartinez/models/i3d"