data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_train_clips.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  window_size: 64

training:
  use_cuda: True
  epochs: 5
  random_seed: 42
  batch_size: 1
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "D:/Thesis/models"