data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "random"
  diagonal_videos_path: None #"/vol/tensusers5/jmartinez/datasets/diagonal_videos.gzip"
  use_diag_videos: False
  final_pooling_size: 512

training:
  extra_conv: True
  model_weights: "baseline_imagenet_JA-A_GEBAREN-A_50_128_0.1_SGD/i3d_49_8.pt"
  specific_glosses: [ "JA-A", "GEBAREN-A" ]
  run_name: "test"
  use_cuda: True
  epochs: 50
  random_seed: 42
  batch_size: 16
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "D:/Thesis/models/i3d"
  weights_dir: "D:/Thesis/models"