data:

  cngt_clips_path: "/vol/tensusers5/jmartinez/datasets/cngt_single_signs.zip"
  signbank_path: "/vol/tensusers5/jmartinez/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "/vol/tensusers5/jmartinez/datasets/cngt_vocab.gzip"
  sb_vocab_path: "/vol/tensusers5/jmartinez/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "random"
  diagonal_videos_path: "/vol/tensusers5/jmartinez/datasets/diagonal_videos.gzip"
  use_diag_videos: True

training:
  specific_glosses: ["GEBAREN-A", "JA-A"]
  run_name: ""
  use_cuda: True
  epochs: 50
  random_seed: 42
  batch_size: 128
  init_lr: 0.1
  momentum: 0.9
  weight_decay: 0.0000001
  model_dir: "/vol/tensusers5/jmartinez/models/i3d"
  weights_dir: "/vol/tensusers5/jmartinez/models"
