data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "random"
  diagonal_videos_path: "D:/Thesis/predictions/diagonal_videos.gzip"
  use_diag_videos: False
  final_pooling_size: 1024

test:
  extra_conv: False
  specific_glosses: ["JA-A", "GEBAREN-A"]
  model_dir: "D:Thesis/models/i3d"
  pred_dir: "D:Thesis/tsne/"
  fold: "train"
  use_cuda: True
  run_name: "baseline_imagenet"
  run_batch_size: 128
  random_seed: 42
  optimizer: "SGD"
  lr: 0.1
  epochs: 50
  ckpt_epoch: 49
  ckpt_step: 8
  batch_size: 16
