data:

  cngt_clips_path: "/vol/tensusers5/jmartinez/datasets/cngt_single_signs.zip"
  signbank_path: "/vol/tensusers5/jmartinez/datasets/NGT_Signbank.zip"
  sb_vocab_path: "/vol/tensusers5/jmartinez/datasets/signbank_vocab.gzip"
  window_size: 16
  data_loading: "balanced"
  input_size: 256

test:
  specific_glosses: ["JA-A", "GEBAREN-A"]
  model_dir: "/vol/tensusers5/jmartinez/models/i3d"
  fold: "train"
  use_cuda: True
  run_name: "baseline_imagenet"
  run_batch_size: 128
  random_seed: 42
  optimizer: "SGD"
  lr: 0.1
  epochs: 50
  ckpt_epoch: 49
  batch_size: 128
