pca:
  reference_sign: "PT-1hand:1"
  signs: ["WETEN-A"]
  fold: "test"
  batch_size: 16
  run_name: "test"
  run_batch_size: 128
  run_lr: 0.1
  run_optimizer: "SGD"
  run_epochs: 50
  model_root: "/vol/tensusers5/jmartinez/models/i3d"
  use_cuda: True
  random_seed: 42

data:
  clips_per_class: -1
  root: "/vol/tensusers5/jmartinez/datasets"
  cngt_clips_folder: "cngt_single_signs_256"
  signbank_folder: "NGT_Signbank_256"
  sb_vocab_file: "signbank_vocab.gzip"
  window_size: 16
  loading_mode: "balanced"
  input_size: 256