data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_train_clips.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 16

test:
  model_dir: "D:Thesis/models/i3d"
  pred_dir: "D:Thesis/predictions/i3d"
  fold: "test"
  run_name: "balanced_binary"
  use_cuda: False
  random_seed: 42
  run_batch_size: 128
  optimizer: "SGD"
  lr: 0.1
  epochs: 50
  ckpt_epoch: 49
  ckpt_step: 3
  batch_size: 16
