data:

  cngt_clips_path: "D:/Thesis/datasets/cngt_single_signs.zip"
  signbank_path: "D:/Thesis/datasets/NGT_Signbank_resized.zip"
  cngt_vocab_path: "D:/Thesis/datasets/cngt_vocab.gzip"
  sb_vocab_path: "D:/Thesis/datasets/signbank_vocab.gzip"
  window_size: 8
  data_loading: "random"
  diagonal_videos_path: None #"D:/Thesis/predictions/diagonal_videos.gzip"
  use_diag_videos: False
  save_predictions: True
  input_size: 256

test:
  specific_glosses: ["JA-A", "GEBAREN-A"]
  model_dir: "D:Thesis/models/i3d"
  pred_dir: "D:Thesis/predictions/i3d"
  fold: "test"
  run_name: "12fps"
  use_cuda: True
  random_seed: 42
  run_batch_size: 128
  optimizer: "SGD"
  lr: 0.1
  epochs: 50
  ckpt_epoch: 49
  batch_size: 16
